all:
  children:
    windows:
      hosts:
        srv-ad-01:
          ansible_host: 10.8.40.10
        srv-ad-02:
          ansible_host: 10.8.40.11
        srv-wsus-01:
          ansible_host: 10.8.40.20

    domain_controllers:
      hosts:
        srv-ad-01:
        srv-ad-02:

    primary_dc:
      hosts:
        srv-ad-01:

    secondary_dcs:
      hosts:
        srv-ad-02:

    wsus_servers:
      hosts:
        srv-wsus-01:

    member_servers:
      hosts:
        srv-wsus-01: