all:
  children:
    windows:
      hosts:
        srv-dc-01:
          ansible_host: 10.8.40.10
        srv-dc-02:
          ansible_host: 10.8.40.11
        srv-wsus-01:
          ansible_host: 10.8.40.20

    domain_controllers:
      hosts:
        srv-dc-01:
        srv-dc-02:

    primary_dc:
      hosts:
        srv-dc-01:

    secondary_dcs:
      hosts:
        srv-dc-02:

    wsus_servers:
      hosts:
        srv-wsus-01:

    member_servers:
      hosts:
        srv-wsus-01: